### ISSUE TITLE
tv域名无法使用

### ISSUE THREAD

**Issue by realth000** [iota9star/mikan_flutter#47]
tv域名相关调用接口是否需要更新呢？目前无法登录，也无法加载任何图片（看上去和#42）一样。

调用图片返回的是404

```
======== Exception caught by image resource service ================================================
The following NetworkImageLoadException was thrown resolving an image codec:
HTTP request failed, statusCode: 404, https://mikanime.tv/images/Bangumi/202304/eba13feb.jpg

When the exception was thrown, this was the stack: 
#0      CacheImage._loadAsync (package:mikan/internal/image_provider.dart:158:9)
<asynchronous suspension>
Image provider: CacheImage("https://mikanime.tv/images/Bangumi/202304/eba13feb.jpg", scale: 1.0)
Image key: CacheImage("https://mikanime.tv/images/Bangumi/202304/eba13feb.jpg", scale: 1.0)
```

登录的话会显示登录成功，但是页面回去以后右上角头像依然是默认未登录头像，点开也已依然是“hi 请登录”

接口返回的是302

```
flutter:  D  16:44:26.952 new _Http.() (package:mikan/internal/http.dart:103:30) 
flutter:  D  16:44:27.137 new _Http.() (package:mikan/internal/http.dart:103:30) *** Request ***
flutter:  D  16:44:27.137 new _Http.() (package:mikan/internal/http.dart:103:30) uri: https://mikanime.tv/Account/Login?ReturnUrl=%2F
flutter:  D  16:44:27.137 new _Http.() (package:mikan/internal/http.dart:103:30) 
flutter:  D  16:44:31.091 new _Http.() (package:mikan/internal/http.dart:103:30) *** DioException ***:
flutter:  D  16:44:31.091 new _Http.() (package:mikan/internal/http.dart:103:30) uri: https://mikanime.tv/Account/Login?ReturnUrl=%2F
flutter:  D  16:44:31.091 new _Http.() (package:mikan/internal/http.dart:103:30) DioException [bad response]: The request returned an invalid status code of 302.
flutter:  D  16:44:31.092 new _Http.() (package:mikan/internal/http.dart:103:30) uri: https://mikanime.tv/Account/Login?ReturnUrl=%2F
flutter:  D  16:44:31.092 new _Http.() (package:mikan/internal/http.dart:103:30) 
flutter:  D  16:44:31.092 new _Http.() (package:mikan/internal/http.dart:103:30) 
flutter:  E  16:44:31.092 Http._request (package:mikan/internal/http.dart:164:9) 
════════════════════════════════════════════════════════════════════════════════════════════════════
DioException [bad response]: The request returned an invalid status code of 302.

#0      DioMixin.fetch.<anonymous closure> (package:dio/src/dio_mixin.dart:507:7)
#1      _RootZone.runUnary (dart:async/zone.dart:1661:54)
#2      _FutureListener.handleError (dart:async/future_impl.dart:174:22)
#3      Future._propagateToListeners.handleError (dart:async/future_impl.dart:852:47)
#4      Future._propagateToListeners (dart:async/future_impl.dart:873:13)
#5      Future._completeError (dart:async/future_impl.dart:649:5)
#6      _SyncCompleter._completeError (dart:async/future_impl.dart:60:12)
#7      _Completer.completeError (dart:async/future_impl.dart:26:5)
#8      Future.any.onError (dart:async/future.dart:620:45)
#9      _RootZone.runBinary (dart:async/zone.dart:1666:54)
#10     _FutureListener.handleError (dart:async/future_impl.dart:171:22)
#11     Future._propagateToListeners.handleError (dart:async/future_impl.dart:852:47)
#12     Future._propagateToListeners (dart:async/future_impl.dart:873:13)
#13     Future._completeError (dart:async/future_impl.dart:649:5)
#14     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:739:7)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#18     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
#19     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#20     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

════════════════════════════════════════════════════════════════════════════════════════════════════

flutter:  D  16:44:31.093 LoginModel.submit (package:mikan/providers/login_model.dart:71:5) notify...
flutter:  D  16:44:31.097 _MikanAppState._buildMaterialApp.().() (package:mikan/main.dart:176:20) route change: /login => null
flutter:  D  16:44:31.098 _MikanAppState._buildMaterialApp.().() (package:mikan/main.dart:176:20) route change: null => /index
flutter:  D  16:44:31.289 new _Http.() (package:mikan/internal/http.dart:103:30) *** Request ***
flutter:  D  16:44:31.290 new _Http.() (package:mikan/internal/http.dart:103:30) uri: https://mikanime.tv
flutter:  D  16:44:31.290 new _Http.() (package:mikan/internal/http.dart:103:30) 
flutter:  D  16:44:31.339 ChangeNotifierProvider._dispose (package:provider/src/change_notifier_provider.dart:133:15) disposed.
flutter:  D  16:44:31.443 LoginModel.dispose (package:mikan/providers/login_model.dart:91:11) disposed.
flutter:  D  16:44:31.512 new _Http.() (package:mikan/internal/http.dart:103:30) *** Request ***
flutter:  D  16:44:31.512 new _Http.() (package:mikan/internal/http.dart:103:30) uri: https://mikanime.tv/Home/EpisodeUpdateRows?predate=-1&enddate=-1&maximumitems=16
flutter:  D  16:44:31.512 new _Http.() (package:mikan/internal/http.dart:103:30) 
```

切换成主站.me以后一切正常

测试环境：

* OS: Arch linux / MIUI14(android13)
* Flutter version: 3.13.2
* Revision: 1c091e144d6da25ef43b3a107c87adc4af56b03f

**Comment by realth000** [comment]
失算了，还是代理的问题，彻底关掉以后tv就好用了（
